In [8]:
import numpy as np

In [1]:
def gf2_rank(rows):
    """
    Find rank of a matrix over GF2.

    The rows of the matrix are given as nonnegative integers, thought
    of as bit-strings.

    This function modifies the input list. Use gf2_rank(rows.copy())
    instead of gf2_rank(rows) to avoid modifying rows.
    """
    rank = 0
    while rows:
        pivot_row = rows.pop()
        if pivot_row:
            rank += 1
            lsb = pivot_row & -pivot_row
            for index, row in enumerate(rows):
                if row & lsb:
                    rows[index] = row ^ pivot_row
    return rank

In [27]:
import random

def random_matrix():
    return [random.getrandbits(4) for row in range(4)]

def random_matrices(count):
    return [random_matrix() for _ in range(count)]

In [62]:
from numpy.linalg import matrix_power
from numpy.linalg import matrix_rank
l = 24
P_l = np.zeros((l,l),dtype=int)
P_l[0,l-1] = 1
P_l[1:l,0:l-1] = np.eye(l-1, dtype=int)
A_part = (np.eye(l, dtype=int) + matrix_power(P_l,2) + matrix_power(P_l,8) + matrix_power(P_l,15))%2
B_part = (np.eye(l, dtype=int) + matrix_power(P_l,2) + matrix_power(P_l,12) + matrix_power(P_l,17))%2
H_X = np.concatenate((A_part, B_part), axis=1)
# H_Z = np.concatenate((np.transpose(B_part), np.transpose(A_part)), axis=1)
# H_XZ = np.zeros((2*l,4*l), dtype = int)
# H_XZ[0:l, 0:2*l] = H_X
# H_XZ[l:2*l, 2*l:4*l] = H_Z

# from array of binaries to decimal
n_row = np.size(H_X,axis=0)
H_Xb = []
for i_r in range(n_row):
    H_Xb.append(np.sum(H_X[i_r,:]* 2**np.arange(47,-1,-1)))

# from decimal to array of binaries
n = 48 ## number of data qubits
H_X_out = np.zeros((len(H_Xb),n),dtype=int)
for i_1, number in enumerate(H_Xb):
    num_str=np.base_repr(number,base=2)[::-1]
    for i_2 in range(len(num_str)):
        H_X_out[i_1,N-i_2-1]=int(num_str[i_2])

        
# print(H_Xb)
# print(H_X)        
print(np.linalg.norm(H_X_out-H_X))
        
H_Xb2 = []      
for i_r in range(n_row):
    H_Xb2.append(np.sum(H_X_out[i_r,:]* 2**np.arange(47,-1,-1)))
# print(H_Xb2)


# print(gf2_rank(H_Xb.copy()))

0.0


In [71]:
import timeit

count = 4
number = 10
ms = random_matrix()
print(ms)
# for n in range(len(ms)):
#     print(np.base_repr(np.array(ms[n]),base=2))

# timer = timeit.Timer(
#     setup="ms = random_matrices({})".format(count),
#     stmt="[gf2_rank(m.copy()) for m in ms]",
#     globals=globals())
# print(min(timer.repeat(number=number)) / count / number)

N = 4 ## number of data qubits
ms_out = np.zeros((len(ms),N))
for i_1, number in enumerate(ms):
    num_str=np.base_repr(number,base=2)[::-1]
    for i_2 in range(len(num_str)):
        ms_out[i_1,N-i_2-1]=int(num_str[i_2])
print(ms_out)
        
H_Xb2 = []      
for i_r in range(count):
    H_Xb2.append(np.sum(ms_out[i_r,:]* 2**np.arange(N-1,-1,-1)))
print(H_Xb2)

[7, 10, 3, 12]
[[0. 1. 1. 1.]
 [1. 0. 1. 0.]
 [0. 0. 1. 1.]
 [1. 1. 0. 0.]]
[7.0, 10.0, 3.0, 12.0]
